### ISSUE TITLE
Notes on StarSpace

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#10]
Some comments, not sure if intentional:

1.) Why is the embedding only 10d? This would explain low performance, 10d is way too low. I'd suggest 256d at least.

2.) What has this to do with the unifying approaches? This is just another embedding algorithm, like e.g., node2vec, does it fit into that section, really?

**Comment by vpodpecan** [comment]
1) Nope, you are mistaken. Increasing 10 times (100D) makes it worse. This makes sense because the texts are quite short and more dimensions cannot help.
2) The justification in the book is that here we can embedd anything and also embedd different entities into the same space. If this really makes it unifying I cannot say...

**Comment by SkBlaz** [comment]
Do you have a reference or a proof for 1.)? Would be interesting to see the
claim somewhere published, as the opposite was published it seems (will
find ref)

**Comment by SkBlaz** [comment]
https://papers.nips.cc/paper/2018/file/b534ba68236ba543ae44b22bd110a1d6-Paper.pdf

https://www.aclweb.org/anthology/I17-2006/

https://www.aclweb.org/anthology/W19-4328.pdf (o kompresiji)
